

const AboutCompany = () =>{
    return(
        <>
            <h2>About Company Details</h2>
            <div>
                <h5>History:</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit consectetur culpa, exercitationem officiis, error soluta fuga eligendi maiores ipsam voluptatibus quia quidem doloribus corporis eos odio rerum sit nisi obcaecati. Nostrum aliquam soluta culpa sint iste. Doloribus expedita inventore architecto necessitatibus adipisci quaerat dolore, praesentium, possimus eligendi voluptates temporibus asperiores voluptatem optio veritatis ullam eaque omnis vitae corporis distinctio cupiditate saepe pariatur tempore doloremque quas. Deleniti, est similique? Dolorem cum voluptates provident exercitationem, libero ipsum accusantium totam sit deleniti repellendus nemo incidunt impedit. Non quos voluptatem fugiat impedit incidunt excepturi possimus, inventore, placeat aspernatur quia nesciunt quae, magni vero aperiam. Aut, nam accusantium temporibus omnis eaque mollitia incidunt vel excepturi enim labore rem, dolorem maiores placeat ipsa! Labore ad explicabo, dolore impedit tempora perspiciatis illum cum vel dolorum optio id molestiae eos reiciendis nobis veniam quae sapiente et ipsa blanditiis, quidem ullam nisi! Tempore vero quod molestias nobis numquam! Obcaecati ut maxime similique explicabo voluptas nobis, adipisci, nulla deserunt nisi veniam sit maiores error repellat eveniet officia consequatur, harum tenetur eos. Voluptas at dicta nisi et quibusdam aperiam saepe ad accusantium ab, repellendus porro atque nostrum vitae fugiat possimus ducimus veniam hic, soluta labore ipsum. Veniam cumque repellendus laborum quidem!</p>

                <h5>Achievements:</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit consectetur culpa, exercitationem officiis, error soluta fuga eligendi maiores ipsam voluptatibus quia quidem doloribus corporis eos odio rerum sit nisi obcaecati. Nostrum aliquam soluta culpa sint iste. Doloribus expedita inventore architecto necessitatibus adipisci quaerat dolore, praesentium, possimus eligendi voluptates temporibus asperiores voluptatem optio veritatis ullam eaque omnis vitae corporis distinctio cupiditate saepe pariatur tempore doloremque quas. Deleniti, est similique? Dolorem cum voluptates provident exercitationem, libero ipsum accusantium totam sit deleniti repellendus nemo incidunt impedit. Non quos voluptatem fugiat impedit incidunt excepturi possimus, inventore, placeat aspernatur quia nesciunt quae, magni vero aperiam. Aut, nam accusantium temporibus omnis eaque mollitia incidunt vel excepturi enim labore rem, dolorem maiores placeat ipsa! Labore ad explicabo, dolore impedit tempora perspiciatis illum cum vel dolorum optio id molestiae eos reiciendis nobis veniam quae sapiente et ipsa blanditiis, quidem ullam nisi! Tempore vero quod molestias nobis numquam! Obcaecati ut maxime similique explicabo voluptas nobis, adipisci, nulla deserunt nisi veniam sit maiores error repellat eveniet officia consequatur, harum tenetur eos. Voluptas at dicta nisi et quibusdam aperiam saepe ad accusantium ab, repellendus porro atque nostrum vitae fugiat possimus ducimus veniam hic, soluta labore ipsum. Veniam cumque repellendus laborum quidem!</p>
                
                <h5>Management Message:</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit consectetur culpa, exercitationem officiis, error soluta fuga eligendi maiores ipsam voluptatibus quia quidem doloribus corporis eos odio rerum sit nisi obcaecati. Nostrum aliquam soluta culpa sint iste. Doloribus expedita inventore architecto necessitatibus adipisci quaerat dolore, praesentium, possimus eligendi voluptates temporibus asperiores voluptatem optio veritatis ullam eaque omnis vitae corporis distinctio cupiditate saepe pariatur tempore doloremque quas. Deleniti, est similique? Dolorem cum voluptates provident exercitationem, libero ipsum accusantium totam sit deleniti repellendus nemo incidunt impedit. Non quos voluptatem fugiat impedit incidunt excepturi possimus, inventore, placeat aspernatur quia nesciunt quae, magni vero aperiam. Aut, nam accusantium temporibus omnis eaque mollitia incidunt vel excepturi enim labore rem, dolorem maiores placeat ipsa! Labore ad explicabo, dolore impedit tempora perspiciatis illum cum vel dolorum optio id molestiae eos reiciendis nobis veniam quae sapiente et ipsa blanditiis, quidem ullam nisi! Tempore vero quod molestias nobis numquam! Obcaecati ut maxime similique explicabo voluptas nobis, adipisci, nulla deserunt nisi veniam sit maiores error repellat eveniet officia consequatur, harum tenetur eos. Voluptas at dicta nisi et quibusdam aperiam saepe ad accusantium ab, repellendus porro atque nostrum vitae fugiat possimus ducimus veniam hic, soluta labore ipsum. Veniam cumque repellendus laborum quidem!</p>
            </div>
        </>
    )
}

export default AboutCompany;